spring.datasource.url=jdbc:sqlserver://DESKTOP-C8QJVNP;instanceName=SQLEXPRESS;databaseName=pfadb;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.username=sa
spring.datasource.password=Pfa2025!SqlServer

# En prod, on veut que le schéma vienne de schema.sql (SQL Server Management)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=false



# Exécute schema.sql au démarrage (création tables)
spring.sql.init.mode=always
spring.sql.init.platform=mssql
spring.sql.init.schema-locations=classpath:schema_server_tables_only.sql

